/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesIndexRouteImport } from './routes/venues/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as VenuesSlugRouteImport } from './routes/venues/$slug'
import { Route as DashboardVenuesRouteImport } from './routes/dashboard/venues'
import { Route as DashboardReservationsRouteImport } from './routes/dashboard/reservations'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardEmployeesRouteImport } from './routes/dashboard/employees'
import { Route as DashboardArrivalsRouteImport } from './routes/dashboard/arrivals'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as VenuesSlugReservationRouteImport } from './routes/venues/$slug/reservation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVenuesRoute = DashboardVenuesRouteImport.update({
  id: '/dashboard/venues',
  path: '/dashboard/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReservationsRoute = DashboardReservationsRouteImport.update({
  id: '/dashboard/reservations',
  path: '/dashboard/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/dashboard/events',
  path: '/dashboard/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/dashboard/employees',
  path: '/dashboard/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardArrivalsRoute = DashboardArrivalsRouteImport.update({
  id: '/dashboard/arrivals',
  path: '/dashboard/arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugReservationRoute = VenuesSlugReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => VenuesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/arrivals': typeof DashboardArrivalsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/venues/$slug': typeof VenuesSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/venues/$slug/reservation': typeof VenuesSlugReservationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/arrivals': typeof DashboardArrivalsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/venues/$slug': typeof VenuesSlugRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/venues/$slug/reservation': typeof VenuesSlugReservationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/arrivals': typeof DashboardArrivalsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/venues/$slug': typeof VenuesSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/venues/$slug/reservation': typeof VenuesSlugReservationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/dashboard/arrivals'
    | '/dashboard/employees'
    | '/dashboard/events'
    | '/dashboard/reservations'
    | '/dashboard/venues'
    | '/venues/$slug'
    | '/dashboard/'
    | '/venues/'
    | '/venues/$slug/reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/dashboard/arrivals'
    | '/dashboard/employees'
    | '/dashboard/events'
    | '/dashboard/reservations'
    | '/dashboard/venues'
    | '/venues/$slug'
    | '/dashboard'
    | '/venues'
    | '/venues/$slug/reservation'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/dashboard/arrivals'
    | '/dashboard/employees'
    | '/dashboard/events'
    | '/dashboard/reservations'
    | '/dashboard/venues'
    | '/venues/$slug'
    | '/dashboard/'
    | '/venues/'
    | '/venues/$slug/reservation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  DashboardArrivalsRoute: typeof DashboardArrivalsRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardReservationsRoute: typeof DashboardReservationsRoute
  DashboardVenuesRoute: typeof DashboardVenuesRoute
  VenuesSlugRoute: typeof VenuesSlugRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/venues': {
      id: '/dashboard/venues'
      path: '/dashboard/venues'
      fullPath: '/dashboard/venues'
      preLoaderRoute: typeof DashboardVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reservations': {
      id: '/dashboard/reservations'
      path: '/dashboard/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof DashboardReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/dashboard/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/dashboard/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/arrivals': {
      id: '/dashboard/arrivals'
      path: '/dashboard/arrivals'
      fullPath: '/dashboard/arrivals'
      preLoaderRoute: typeof DashboardArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug/reservation': {
      id: '/venues/$slug/reservation'
      path: '/reservation'
      fullPath: '/venues/$slug/reservation'
      preLoaderRoute: typeof VenuesSlugReservationRouteImport
      parentRoute: typeof VenuesSlugRoute
    }
  }
}

interface VenuesSlugRouteChildren {
  VenuesSlugReservationRoute: typeof VenuesSlugReservationRoute
}

const VenuesSlugRouteChildren: VenuesSlugRouteChildren = {
  VenuesSlugReservationRoute: VenuesSlugReservationRoute,
}

const VenuesSlugRouteWithChildren = VenuesSlugRoute._addFileChildren(
  VenuesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  DashboardArrivalsRoute: DashboardArrivalsRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardReservationsRoute: DashboardReservationsRoute,
  DashboardVenuesRoute: DashboardVenuesRoute,
  VenuesSlugRoute: VenuesSlugRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
